### ISSUE TITLE
Overloaded object?

### ISSUE THREAD

**Issue by michaelreynolds** [yllumi/PyroCMS-Download#1]
I tried installing this addon, but I'm getting these errors. I thought I ask you before I dive in too deeply. I've also got other plugins installed. I'm running Pyro Version 2.2.1. Any ideas what's happening here?

A PHP Error was encountered
Severity: Notice
Message: Undefined property: CI::$data
Filename: MX/Controller.php
Line Number: 57

A PHP Error was encountered
Severity: Notice
Message: Indirect modification of overloaded property Admin::$data has no effect
Filename: controllers/admin.php
Line Number: 70

Fatal error: Cannot assign by reference to overloaded object in addons/shared_addons/modules/Download/controllers/admin.php on line 70

**Comment by yllumi** [comment]
I think I know what happen.
Wait a minute and I will fix it.

**Comment by yllumi** [comment]
This is a fixed commit b46997263dbd61a11eea27a24d852fc1d737b867
You can tell here if it's still error.
If it is done we can then close the issue, @michaelreynolds :)

**Comment by michaelreynolds** [comment]
Great, yes that works a lot better, but now I'm not getting a page response for /admin/download/add. Any ideas?

**Comment by yllumi** [comment]
what is the error? here there is no problem for showing add form. is it a blank page?

**Comment by michaelreynolds** [comment]
Ya, it's a blank page. Not found.

**Comment by yllumi** [comment]
have you check my latest commit?
And I consider you to upgrade to the latest 2.2x version. :)
